using System.Text.Json.Serialization;

#nullable enable

namespace AssemblyAI;

public class LemurSummaryResponse
{
    /// <summary>
    /// The response generated by LeMUR
    /// </summary>
    [JsonPropertyName("response")]
    public string Response { get; init; }

    /// <summary>
    /// The ID of the LeMUR request
    /// </summary>
    [JsonPropertyName("request_id")]
    public string RequestId { get; init; }
}
