using System.Text.Json.Serialization;
using AssemblyAI;

#nullable enable

namespace AssemblyAI;

public class LemurActionItemsResponse
{
    /// <summary>
    /// The response generated by LeMUR
    /// </summary>
    [JsonPropertyName("response")]
    public string Response { get; init; }

    /// <summary>
    /// The ID of the LeMUR request
    /// </summary>
    [JsonPropertyName("request_id")]
    public string RequestId { get; init; }

    /// <summary>
    /// The usage numbers for the LeMUR request
    /// </summary>
    [JsonPropertyName("usage")]
    public LemurUsage Usage { get; init; }
}
