name: ci

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.201

      - name: Restore dependencies
        run: dotnet restore src

      - name: Build solution
        run: dotnet build src --no-restore
